name: flutter_device_apps_android
description: Android implementation of flutter_device_apps (federated plugin).
version: 0.4.0

repository: https://github.com/okmsbun/flutter_device_apps_android
issue_tracker: https://github.com/okmsbun/flutter_device_apps_android/issues
topics:
  - flutter
  - plugin
  - android
  - broadcast-receiver
  - intent-actions

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_apps_platform_interface: ^0.4.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: flutter_device_apps
    platforms:
      android:
        package: com.okmsbun.flutter_device_apps_android
        pluginClass: FlutterDeviceAppsAndroidPlugin
        dartPluginClass: FlutterDeviceAppsAndroid
